from camelcase import camelcase


def test_camelcase():
    assert camelcase('foo') == 'foo'
    assert camelcase('foo-bar') == 'fooBar'
    assert camelcase('foo-bar-baz') == 'fooBarBaz'
    assert camelcase('foo--bar') == 'fooBar'
    assert camelcase('--foo-bar') == 'fooBar'
    assert camelcase('--foo--bar') == 'fooBar'
    assert camelcase('FOO-BAR') == 'fooBar'
    assert camelcase('FOÈ-BAR') == 'foèBar'
    assert camelcase('-foo-bar-') == 'fooBar'
    assert camelcase('--foo--bar--') == 'fooBar'
    assert camelcase('foo.bar') == 'fooBar'
    assert camelcase('foo..bar') == 'fooBar'
    assert camelcase('..foo..bar..') == 'fooBar'
    assert camelcase('foo_bar') == 'fooBar'
    assert camelcase('__foo__bar__') == 'fooBar'
    assert camelcase('__foo__bar__') == 'fooBar'
    assert camelcase('foo bar') == 'fooBar'
    assert camelcase('  foo  bar  ') == 'fooBar'
    assert camelcase('-') == '-'
    assert camelcase(' - ') == '-'
    assert camelcase('fooBar') == 'fooBar'
    assert camelcase('fooBar-baz') == 'fooBarBaz'
    assert camelcase('foìBar-baz') == 'foìBarBaz'
    assert camelcase('fooBarBaz-bazzy') == 'fooBarBazBazzy'
    assert camelcase('FBBazzy') == 'fbBazzy'
    assert camelcase('F') == 'f'
    assert camelcase('FooBar') == 'fooBar'
    assert camelcase('Foo') == 'foo'
    assert camelcase('FOO') == 'foo'
    assert camelcase(['foo', 'bar']) == 'fooBar'
    assert camelcase(['foo', '-bar']) == 'fooBar'
    assert camelcase(['foo', '-bar', 'baz']) == 'fooBarBaz'
    assert camelcase(['', '']) == ''
    assert camelcase('--') == ''
    assert camelcase('') == ''
    assert camelcase('--__--_--_') == ''
    assert camelcase(['---_', '--', '', '-_- ']) == ''
    assert camelcase('foo bar?') == 'fooBar?'
    assert camelcase('foo bar!') == 'fooBar!'
    assert camelcase('foo bar$') == 'fooBar$'
    assert camelcase('foo-bar#') == 'fooBar#'
    assert camelcase('foo2bar') == 'foo2Bar'
    assert camelcase('XMLHttpRequest') == 'xmlHttpRequest'
    assert camelcase('AjaxXMLHttpRequest') == 'ajaxXmlHttpRequest'
    assert camelcase('Ajax-XMLHttpRequest') == 'ajaxXmlHttpRequest'
    assert camelcase([]) == ''
    assert camelcase('mGridCol6@md') == 'mGridCol6@md'
    assert camelcase('A::a') == 'a::a'
    assert camelcase('Hello1World') == 'hello1World'
    assert camelcase('Hello11World') == 'hello11World'
    assert camelcase('hello1world') == 'hello1World'
    assert camelcase('Hello1World11foo') == 'hello1World11Foo'
    assert camelcase('Hello1') == 'hello1'
    assert camelcase('hello1') == 'hello1'
    assert camelcase('1Hello') == '1Hello'
    assert camelcase('1hello') == '1Hello'
    assert camelcase('h2w') == 'h2W'


def test_camelcase_with_pascalCase_option():
    assert camelcase('foo', pascalCase=True) == 'Foo'
    assert camelcase('foo-bar', pascalCase=True) == 'FooBar'
    assert camelcase('foo-bar-baz', pascalCase=True) == 'FooBarBaz'
    assert camelcase('foo--bar', pascalCase=True) == 'FooBar'
    assert camelcase('--foo-bar', pascalCase=True) == 'FooBar'
    assert camelcase('--foo--bar', pascalCase=True) == 'FooBar'
    assert camelcase('FOO-BAR', pascalCase=True) == 'FooBar'
    assert camelcase('FOÈ-BAR', pascalCase=True) == 'FoèBar'
    assert camelcase('-foo-bar-', pascalCase=True) == 'FooBar'
    assert camelcase('--foo--bar--', pascalCase=True) == 'FooBar'
    assert camelcase('foo.bar', pascalCase=True) == 'FooBar'
    assert camelcase('foo..bar', pascalCase=True) == 'FooBar'
    assert camelcase('..foo..bar..', pascalCase=True) == 'FooBar'
    assert camelcase('foo_bar', pascalCase=True) == 'FooBar'
    assert camelcase('__foo__bar__', pascalCase=True) == 'FooBar'
    assert camelcase('__foo__bar__', pascalCase=True) == 'FooBar'
    assert camelcase('foo bar', pascalCase=True) == 'FooBar'
    assert camelcase('  foo  bar  ', pascalCase=True) == 'FooBar'
    assert camelcase('-', pascalCase=True) == '-'
    assert camelcase(' - ', pascalCase=True) == '-'
    assert camelcase('fooBar', pascalCase=True) == 'FooBar'
    assert camelcase('fooBar-baz', pascalCase=True) == 'FooBarBaz'
    assert camelcase('foìBar-baz', pascalCase=True) == 'FoìBarBaz'
    assert camelcase('fooBarBaz-bazzy', pascalCase=True) == 'FooBarBazBazzy'
    assert camelcase('FBBazzy', pascalCase=True) == 'FbBazzy'
    assert camelcase('F', pascalCase=True) == 'F'
    assert camelcase('FooBar', pascalCase=True) == 'FooBar'
    assert camelcase('Foo', pascalCase=True) == 'Foo'
    assert camelcase('FOO', pascalCase=True) == 'Foo'
    assert camelcase(['foo', 'bar'], pascalCase=True) == 'FooBar'
    assert camelcase(['foo', '-bar'], pascalCase=True) == 'FooBar'
    assert camelcase(['foo', '-bar', 'baz'], pascalCase=True) == 'FooBarBaz'
    assert camelcase(['', ''], pascalCase=True) == ''
    assert camelcase('--', pascalCase=True) == ''
    assert camelcase('', pascalCase=True) == ''
    assert camelcase('--__--_--_', pascalCase=True) == ''
    assert camelcase(['---_', '--', '', '-_- '], pascalCase=True) == ''
    assert camelcase('foo bar?', pascalCase=True) == 'FooBar?'
    assert camelcase('foo bar!', pascalCase=True) == 'FooBar!'
    assert camelcase('foo bar$', pascalCase=True) == 'FooBar$'
    assert camelcase('foo-bar#', pascalCase=True) == 'FooBar#'
    assert camelcase('foo2bar', pascalCase=True) == 'Foo2Bar'
    assert camelcase('XMLHttpRequest', pascalCase=True) == 'XmlHttpRequest'
    assert camelcase('AjaxXMLHttpRequest',
                     pascalCase=True) == 'AjaxXmlHttpRequest'
    assert camelcase('Ajax-XMLHttpRequest',
                     pascalCase=True) == 'AjaxXmlHttpRequest'
    assert camelcase([], pascalCase=True) == ''
    assert camelcase('mGridCol6@md', pascalCase=True) == 'MGridCol6@md'
    assert camelcase('A::a', pascalCase=True) == 'A::a'
    assert camelcase('Hello1World', pascalCase=True) == 'Hello1World'
    assert camelcase('Hello11World', pascalCase=True) == 'Hello11World'
    assert camelcase('hello1world', pascalCase=True) == 'Hello1World'
    assert camelcase('hello1World', pascalCase=True) == 'Hello1World'
    assert camelcase('hello1', pascalCase=True) == 'Hello1'
    assert camelcase('Hello1', pascalCase=True) == 'Hello1'
    assert camelcase('1hello', pascalCase=True) == '1Hello'
    assert camelcase('1Hello', pascalCase=True) == '1Hello'
    assert camelcase('h1W', pascalCase=True) == 'H1W'
